### ISSUE TITLE
Can't en passant AI's extra row of pawns

### ISSUE THREAD

**Issue by josephcsible** [dtsudo/Chess-Comp-Stomp-with-Hacks-Web-Browser-Version#1]
![image](https://user-images.githubusercontent.com/16061266/227690452-e47ce0f1-b40d-4549-9647-9bc5f6261629.png)

In the first game where the AI gets an extra row of pawns, I tried to en passant one of them but I couldn't.

**Comment by dtsudo** [comment]
Hmm yeah, in the next version, I'll update the code to allow the player to capture the opponent's pawns en passant if they move 2 spaces forward.

However, I'm also considering disallowing the AI from using en-passant on the player's pawns if they move 3 spaces or if they start on a non-standard rank. So this would be something only the player can do to the AI.

**Comment by dtsudo** [comment]
Thanks for filing the issue!

Version 1.02 was released over the last few days. In this update, you can now capture pawns en passant even if the pawns didn't start on the 2nd rank: https://dtsudo.itch.io/chess-comp-stomp-with-hacks
